name: Generate Semantic Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          

      - name: Setup dependencies
        run: |
          npm install --save-dev @semantic-release/changelog \
                                      @semantic-release/git \
                                      @semantic-release/exec \
                                      @semantic-release/github      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: "KerollesFathy"
          GIT_AUTHOR_EMAIL: "example@gmail.com"
          GIT_COMMITTER_NAME: "KerollesFathy"
          GIT_COMMITTER_EMAIL: "example@gmail.com"
        run: npx semantic-release